#!/usr/bin/env bash
set -x
date
export PS4='+ $SECONDS + '
#
export task_id=${task_id:-'ic'}
#
# source the config cascade
source ${EXPDIR}/exp.setup
source ${EXPDIR}/config/config.${MACHINE}
source ${EXPDIR}/config/config.base
[[ -s ${EXPDIR}/config/config.${task_id} ]] && source ${EXPDIR}/config/config.${task_id}
#
export pid=${pid:-$$}
export RUN=${RUN:-rrfs}
export jobid=${jobid:-${RUN}_${task_id}_${cyc}}

export DATA=${DATA:-${DATAROOT}/${jobid}}
if [ -d ${DATA} ]; then #remove the ${DATA} directory before a new run
  rm -rf ${DATA}
fi
mkdir -p ${DATA}
#
export COMINgfs=${COMINgfs:-$(compath.py $envir/gfs/$gfs_ver)}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc})}
mkdir -p ${COMOUT}/${task_id}
#
#----------------------------------------
# Execute the script.
#----------------------------------------
export pgmout="${DATA}/OUTPUT.${task_id}"
$SCRIPTSrrfs/exrrfs_${task_id}.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
cd ${DATAROOT}
KEEPDATA_ic=${KEEPDATA_ic:-${KEEPDATA}}
[[ "${KEEPDATA_ic}" == "NO" ]] && rm -rf ${DATA}
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
