#!/usr/bin/env bash
export PS4="+ $(basename ${BASH_SOURCE})[${LINENO}]:"
set -x
date
#
export task_id='ungrib'
#
# source the config cascade
source ${EXPDIR}/exp.setup
source ${EXPDIR}/config/config.${MACHINE}
source ${EXPDIR}/config/config.base
[[ -s ${EXPDIR}/config/config.${task_id} ]] && source ${EXPDIR}/config/config.${task_id}
#
export pid=${pid:-$$}
export RUN=${RUN:-rrfs}
export jobid=${jobid:-${RUN}_${task_id}_${cyc}}

export DATA=${DATA:-${DATAROOT}/${jobid}}
export DATA=${DATA}/${FHR:-"FHR_not_defined"}
if [ -d ${DATA} ]; then # remove the ${DATA} directory before a new run
  rm -rf ${DATA}
fi
mkdir -p ${DATA}
#
export COMINgfs=${COMINgfs:-$(compath.py $envir/gfs/$gfs_ver)}
export COMINrap=${COMINrap:-$(compath.py $envir/rap/$rap_ver)}
export COMINrrfs1=${COMINrrfs1:-$(compath.py $envir/rrfs1/$rrfs1_ver)}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc})}
mkdir -p ${COMOUT}/${task_id}
#
#----------------------------------------
# Execute the script.
#----------------------------------------
export pgmout="${DATA}/OUTPUT.${task_id}"
$SCRIPTSrrfs/exrrfs_${task_id}.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
cd ${DATAROOT}
KEEPDATA_ungrib=${KEEPDATA_ungrib:-${KEEPDATA}}
[[ "${KEEPDATA_ungrib}" == "NO" ]] && rm -rf ${DATA}
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
