#!/usr/bin/env bash
# Aloha!
#
exp_basedir=/lfs5/BMC/wrfruc/gge/OPSROOT/exp  # ***** require user inputs
comroot=/lfs5/BMC/wrfruc/gge/OPSROOT/com # input and output data as well as logs for tasks
dataroot=/lfs5/BMC/wrfruc/gge/OPSROOT/stmp # contains task workdirs ($DATA) which to be removed immediately upon task completion unless KEEPDATA=yes 
version=1.0.1
net=rrfs_12km
run=rrfs
exp_name=conus12km #if empty, expdir will be setup under ${version}/ directly
tag=c3v95
config_sample=jet_reservation # a config sample from the sample store
#
realtime=fasle
realtime_length=2m  #eg: 2m(months) or 2d(days)
retro_period='2024070200-2024071200'
start_cyc_spinup='03 15'
start_cyc_prod='09 21'
